name: .NET Framework

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Navigate to workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Restore NuGet packages
      run: nuget restore Slacker.sln

    # Build and publish
    - name: Build and Publish WPF App
      run: msbuild.exe Slacker.sln /p:platform="Any CPU" /p:Configuration="Release"
      
    # Deploy
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Slacker
        path: bin\Release
